version: '3.1'
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: office
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: